inherit_from: .rubocop_installed_rails.yml
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false