name: Continuous Integration Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    name: "RSpec"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: install dependent libraries
        run: sudo apt-get install libsqlite3-dev
      - name: install bundler && bundle
        run: gem install bundler && bundle install --jobs 4 --retry 3
      # - name: prep database
      #   run: bin/rails db:schema:load RAILS_ENV=test
      - name: Run Specs
        run: bin/rails spec
